/**
 * Job Handler: itin_wizard_setup
 *
 * Triggered by the portal ITIN wizard (app/portal/wizard) when a client
 * submits ITIN data. The handler runs the same 8-step auto-chain as the
 * external email-gated ITIN form, converging both entry points on one
 * implementation.
 *
 * CONVERGENCE STRATEGY (Phase 0, 2026-04-14 P0.5):
 *   This handler delegates to `POST /api/itin-form-completed` by importing
 *   and invoking the route's POST function directly with a synthetic
 *   NextRequest. That route already implements the 8-step auto-chain:
 *     1. Update CRM contact (changed fields only)
 *     2. Create Drive folder + save data PDF
 *     3. Ensure SD exists + advance to Document Preparation
 *     4. Auto-generate W-7 + 1040-NR + Schedule OI
 *     5. Email team
 *     6. Create task for Luca
 *     7. Update SD history
 *     8. Log action
 *
 *   Both entry points (external email form + portal wizard) now end up in the
 *   same function. A future Phase 1 refactor may extract the 8-step body into
 *   a standalone lib function and reduce the route + this handler to thin
 *   wrappers, but that refactor is out of Phase 0 scope.
 *
 * PAYLOAD:
 *   {
 *     token: string                // Generated by wizard-submit (portal-<slug>-<year>)
 *     submission_id: string        // UUID of the itin_submissions row
 *     account_id?: string | null
 *     contact_id?: string | null
 *     // ... other portal_wizard fields (not required by this handler)
 *   }
 *
 * UNBLOCKS: Damiano Mocellin (Orizzonti LLC, 2026-04-13),
 *           Antonio Truocchio (ATCOACHING LLC, 2026-04-06),
 *           Antony Fioravanti (AWY Company LLC, one-submission-away).
 */

import { NextRequest } from "next/server"
import type { Job, JobResult } from "../queue"
import * as itinFormCompletedRoute from "@/app/api/itin-form-completed/route"

interface ItinWizardPayload {
  token?: string
  submission_id?: string
}

interface ItinRouteStep {
  step: string
  status: string
  detail?: string
}

interface ItinRouteBody {
  ok?: boolean
  results?: ItinRouteStep[]
  error?: string
}

function nowIso(): string {
  return new Date().toISOString()
}

function normalizeStepStatus(status: string): "ok" | "error" | "skipped" {
  if (status === "ok" || status === "error" || status === "skipped") {
    return status
  }
  return "error"
}

export async function handleItinWizardSetup(job: Job): Promise<JobResult> {
  const p = job.payload as ItinWizardPayload

  if (!p.token || !p.submission_id) {
    return {
      steps: [
        {
          name: "validate_payload",
          status: "error",
          detail: `Missing required fields: ${!p.token ? "token " : ""}${!p.submission_id ? "submission_id" : ""}`.trim(),
          timestamp: nowIso(),
        },
      ],
      summary: "ITIN wizard setup failed: invalid payload",
    }
  }

  // Build a synthetic NextRequest matching the body shape the route expects.
  // The route reads body via `await req.json()` and does not inspect headers
  // or cookies, so an empty-header NextRequest is sufficient.
  const req = new NextRequest("http://internal/api/itin-form-completed", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ submission_id: p.submission_id, token: p.token }),
  })

  try {
    const res = await itinFormCompletedRoute.POST(req)
    const body = (await res.json()) as ItinRouteBody
    const now = nowIso()

    const steps: JobResult["steps"] = (body.results ?? []).map((r) => ({
      name: r.step,
      status: normalizeStepStatus(r.status),
      detail: r.detail,
      timestamp: now,
    }))

    if (!res.ok || body.ok === false) {
      steps.push({
        name: "route_response",
        status: "error",
        detail: body.error ?? `HTTP ${res.status}`,
        timestamp: now,
      })
      return {
        steps,
        summary: `ITIN wizard setup failed: ${body.error ?? `HTTP ${res.status}`}`,
      }
    }

    const okCount = steps.filter((s) => s.status === "ok").length
    const errCount = steps.filter((s) => s.status === "error").length
    return {
      steps,
      summary: `ITIN wizard auto-chain: ${okCount} ok, ${errCount} error${errCount === 1 ? "" : "s"}`,
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return {
      steps: [
        {
          name: "invoke_route",
          status: "error",
          detail: msg,
          timestamp: nowIso(),
        },
      ],
      summary: `ITIN wizard setup threw: ${msg}`,
    }
  }
}
