import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { isDashboardUser } from '@/lib/auth'
import { checkRateLimit, getRateLimitKey } from '@/lib/portal/rate-limit'
import {
  attachmentRefsFromChatRow,
  callWorkerWithAttachments,
  capMediaBudget,
  fenceUntrustedContent,
} from '@/lib/ai-agent/attachment-reader'
import type { WorkerImageBlock } from '@/lib/ai-agent/worker-tools'
import { loadRelevantTemplates, formatTemplatesForPrompt } from '@/lib/ai-agent/templates'
import { NextRequest, NextResponse } from 'next/server'

/**
 * POST /api/portal/chat/suggest
 * AI-powered reply suggestion for admin, generated by the agent worker.
 *
 * 1. Loads this client's account context (services, deadlines, payments)
 * 2. Loads conversation history with this client
 * 3. Hands both to callWorker (sonnet-4-6) with a suggest-specific prompt; the
 *    worker pulls past decisions (memory_recall) + SOPs (get_sop) on demand via
 *    its read-only research tools, rather than us pre-loading KB/style context.
 */
export async function POST(request: NextRequest) {
  // Rate limit: max 6 suggestions per minute (AI calls)
  const rl = checkRateLimit(getRateLimitKey(request) + ':suggest', 6, 60_000)
  if (!rl.allowed) {
    return NextResponse.json({ error: 'Too many requests. Please wait.' }, { status: 429, headers: { 'Retry-After': String(rl.retryAfter ?? 10) } })
  }

  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user || !isDashboardUser(user)) {
    return NextResponse.json({ error: 'Dashboard access required' }, { status: 403 })
  }

  if (!process.env.ANTHROPIC_API_KEY && !process.env.OPENAI_API_KEY) {
    return NextResponse.json({ error: 'AI not configured' }, { status: 503 })
  }

  const { account_id, contact_id } = await request.json()
  if (!account_id && !contact_id) {
    return NextResponse.json({ error: 'account_id or contact_id required' }, { status: 400 })
  }

  try {
    // 1. Get client account info (if available)
    let account = null
    let services = null
    let deadlines = null
    let payments = null

    if (account_id) {
      const { data: acct } = await supabaseAdmin
        .from('accounts')
        .select('company_name, entity_type, state_of_formation, status, ein_number')
        .eq('id', account_id)
        .single()
      account = acct

      // 2. Get active services for this client
      const { data: svc } = await supabaseAdmin
        .from('service_deliveries')
        .select('service_name, service_type, stage, status')
        .eq('account_id', account_id)
        .eq('status', 'active')
        .limit(10)
      services = svc

      // 3. Get upcoming deadlines
      const today = new Date().toISOString().split('T')[0]
      const { data: dl } = await supabaseAdmin
        .from('deadlines')
        .select('deadline_type, due_date, status')
        .eq('account_id', account_id)
        .in('status', ['Pending', 'Overdue'])
        .gte('due_date', today)
        .order('due_date')
        .limit(5)
      deadlines = dl

      // 4. Get recent payments
      const { data: pay } = await supabaseAdmin
        .from('payments')
        .select('description, amount, status, due_date')
        .eq('account_id', account_id)
        .order('due_date', { ascending: false })
        .limit(5)
      payments = pay
    }

    // If no account but we have contact, get contact info for context
    let contactInfo = null
    if (!account_id && contact_id) {
      const { data: ct } = await supabaseAdmin
        .from('contacts')
        .select('full_name, email, language, citizenship')
        .eq('id', contact_id)
        .single()
      contactInfo = ct
    }

    // 5. Get this conversation (last 20 messages).
    // Threading model (matches the portal chat GET route): messages live under
    // BOTH account_id and contact_id — admin replies are account-scoped, "person"-
    // tagged client messages are contact-scoped with account_id NULL. When we have
    // both IDs, union the two scopes so the AI sees the FULL thread, not half of it.
    let conversationQuery = supabaseAdmin
      .from('portal_messages')
      .select('sender_type, message, attachment_url, attachment_name, attachments, created_at')
      .order('created_at', { ascending: false })
      .limit(20)

    if (account_id && contact_id) {
      conversationQuery = conversationQuery.or(
        `account_id.eq.${account_id},and(contact_id.eq.${contact_id},account_id.is.null)`
      )
    } else if (account_id) {
      conversationQuery = conversationQuery.eq('account_id', account_id)
    } else {
      conversationQuery = conversationQuery.eq('contact_id', contact_id).is('account_id', null)
    }

    // Filter out internal chat-event system notes (the `<!-- chat-event: -->`
    // marker) — they are written ABOUT the client for staff and are noise for the AI.
    conversationQuery = conversationQuery.not('message', 'ilike', '%<!-- chat-event:%')

    const { data: conversation } = await conversationQuery
    const conversationHistory = (conversation ?? []).reverse()

    // 6. Build the context
    const clientContext = [
      `Company: ${account?.company_name || contactInfo?.full_name || 'Unknown'}`,
      account?.entity_type ? `Entity: ${account.entity_type}` : '',
      account?.state_of_formation ? `State: ${account.state_of_formation}` : '',
      account?.ein_number ? `EIN: ${account.ein_number}` : '',
      '',
      services?.length ? `Active Services:\n${services.map(s => `- ${s.service_name} (${s.status}${s.current_step && s.total_steps ? `, step ${s.current_step}/${s.total_steps}` : ''})`).join('\n')}` : 'No active services.',
      '',
      deadlines?.length ? `Upcoming Deadlines:\n${deadlines.map(d => `- ${d.deadline_type}: ${d.due_date} (${d.status})`).join('\n')}` : 'No upcoming deadlines.',
      '',
      payments?.length ? `Recent Payments:\n${payments.map(p => `- ${p.description || 'Payment'}: $${p.amount} (${p.status})`).join('\n')}` : '',
    ].filter(Boolean).join('\n')

    // Attachment links belong in the transcript. Without them the model can't
    // even tell a file exists, let alone read it — and it would draft a reply to
    // "here's my passport" having never seen a passport.
    const conversationText = conversationHistory
      .map(m => {
        const files = attachmentRefsFromChatRow(m)
          .map(a => `\n   📎 ${a.name} — ${a.id}`)
          .join('')
        return `${m.sender_type === 'admin' ? 'Admin' : 'Client'}: ${m.message}${files}`
      })
      .join('\n')

    // 7. Load relevant approved CRM templates for the client's latest message so
    // the draft is GROUNDED in approved copy instead of invented from scratch.
    // Keyword-matched against the templates / email_templates libraries; best-effort
    // (returns [] on no match). Language soft-boosts a same-language template.
    const lastClientRow = [...conversationHistory].reverse().find((m) => m.sender_type !== 'admin')
    const lastClientMessage = lastClientRow?.message
    const clientLanguage = contactInfo?.language ?? null
    const relevantTemplates = await loadRelevantTemplates(
      lastClientMessage || conversationText,
      { language: clientLanguage, limit: 3 },
    )
    const templatesBlock = formatTemplatesForPrompt(relevantTemplates)

    // 8. Generate the suggestion via the agent worker. callWorker gives the model
    // the read-only research tools (memory_recall, get_sop, CRM/Gmail/Drive search)
    // so it pulls past decisions + SOPs ON DEMAND instead of us pre-loading them.
    const systemPromptOverride = [
      "You are drafting a reply for Antonio to a client's portal message. Before drafting: 1) Call memory_recall with the topic to check relevant past decisions 2) Analyze context triggers (Wise payment → Wise policy, email instead of portal → redirect to portal). Draft in the client's language. Be Antonio — warm, professional, direct. Max 300 words.",
      templatesBlock ? `\n${templatesBlock}` : "",
    ].join("")

    // Screenshots the client shared go straight to the model (it sees them);
    // documents are listed in the transcript above and read on demand via
    // read_portal_attachment (enableDocReads below). Shared with the Portal Chats
    // Worker tab — one harvester, one scope filter, so they can't drift.
    let media: { imageBlocks: WorkerImageBlock[] } = { imageBlocks: [] }
    let lastMessageFiles = ''
    try {
      const { harvestPortalChatAttachments } = await import('@/lib/portal/chat-attachment-harvest')
      const harvested = await harvestPortalChatAttachments({ accountId: account_id, contactId: contact_id })
      const capped = capMediaBudget(harvested.imageBlocks, [])
      media = { imageBlocks: capped.images }
      if (harvested.note) {
        // Client-chosen filenames/links — fence them.
        lastMessageFiles = `\n\n${fenceUntrustedContent('files in this client chat', harvested.note.trim())}`
      }
    } catch (err) {
      console.warn('[suggest] attachment harvest failed (drafting without files):', err)
    }

    const userMessage = `CLIENT ACCOUNT CONTEXT:\n${clientContext}\n\nCONVERSATION:\n${conversationText}${lastMessageFiles}\n\nThe client just sent the last message. Write Antonio's reply:`

    const { reply } = await callWorkerWithAttachments(userMessage, {
      systemPromptOverride,
      // Lets the worker open an attachment from EARLIER in the thread by its link.
      enableDocReads: true,
      // Was 4. Reading an attachment costs a step; a draft that has to look at a
      // file was hitting the ceiling before it got to write anything.
      maxIterations: 6,
      ...(media.imageBlocks.length ? { images: media.imageBlocks } : {}),
    })

    return NextResponse.json({ suggestion: reply, provider: 'anthropic' })
  } catch (err: unknown) {
    console.error('[suggest] Error:', err)
    return NextResponse.json({ error: 'Failed to generate suggestion' }, { status: 500 })
  }
}
