-- Dev Board plain-English card fields (2026-07-16, dev_task 23dd6246)
--
-- business_impact / simple_next_step: AI-written plain-business-English fields
-- shown on the board card next to summary_plain (generated by the shared
-- lib/dev-tracker/plain-summary.ts choke-point on every substantive write).
-- owner / due_date / origin_url: card metadata Antonio asked to see at a glance.
-- origin_url is the in-app back-link to where the job came from (an inbox email,
-- a portal message) — today it is buried inside description text on shared cards.

-- plain_generated_at: when the AI last (re)wrote the plain fields — makes
-- staleness detectable (updated_at > plain_generated_at) for a later sweep.

ALTER TABLE dev_tasks
  ADD COLUMN IF NOT EXISTS business_impact    text,
  ADD COLUMN IF NOT EXISTS simple_next_step   text,
  ADD COLUMN IF NOT EXISTS owner              text,
  ADD COLUMN IF NOT EXISTS due_date           date,
  ADD COLUMN IF NOT EXISTS origin_url         text,
  ADD COLUMN IF NOT EXISTS plain_generated_at timestamptz;
