export const dynamic = "force-dynamic"

import { NextRequest, NextResponse } from "next/server"
import { logCron } from "@/lib/cron-log"
import { reactivateOnHoldTaxReturns } from "@/lib/tax/reactivation"

/**
 * Cron: Tax-season Reactivation
 * Schedule: daily at 9am UTC (see vercel.json)
 *
 * Scans service_deliveries where service_type='Tax Return' AND status='on_hold'
 * and flips any whose account has a paid 2nd installment back to 'active'.
 *
 * Primary trigger is synchronous inside onSecondInstallmentPaid (see
 * lib/installment-handler.ts). This cron exists as a safety net for:
 *   - 2nd installment payments recorded manually or through a channel that
 *     bypasses the installment handler (Stripe reconcile, Mercury sync,
 *     direct SQL corrections)
 *   - Back-dated payments that happen to land on an SD parked by the global
 *     tax_season_paused flag
 *   - Historical drift between `installment` and `description` values
 *
 * Does NOT touch the global `app_settings.tax_season_paused` flag — that's
 * the master switch Antonio flips manually when season reopens.
 */
export async function GET(req: NextRequest) {
  const startTime = Date.now()
  try {
    const authHeader = req.headers.get("authorization")
    const cronSecret = process.env.CRON_SECRET
    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const result = await reactivateOnHoldTaxReturns()

    logCron({
      endpoint: "/api/cron/tax-reactivation",
      status: result.errors > 0 ? "error" : "success",
      duration_ms: Date.now() - startTime,
      details: {
        scanned: result.scanned,
        reactivated: result.reactivated,
        skipped: result.skipped,
        errors: result.errors,
      },
    })

    if (result.reactivated > 0) {
      try {
        const { gmailPost } = await import("@/lib/gmail")
        const reactivatedRows = result.details
          .filter(d => d.action === "reactivated")
          .map(d => `<tr><td style="padding:6px 12px;border:1px solid #ddd">${d.company_name ?? d.account_id}</td><td style="padding:6px 12px;border:1px solid #ddd">on_hold &rarr; active</td></tr>`)
          .join("")
        const errorRows = result.details
          .filter(d => d.action === "error")
          .map(d => `<tr><td style="padding:6px 12px;border:1px solid #ddd;color:#c00">${d.company_name ?? d.account_id}</td><td style="padding:6px 12px;border:1px solid #ddd;color:#c00">${d.error_message ?? "unknown error"}</td></tr>`)
          .join("")
        const subject = `✅ Tax reactivation: ${result.reactivated} SD${result.reactivated === 1 ? "" : "s"}${result.errors > 0 ? ` + ${result.errors} error(s)` : ""}`
        const html = `
          <h2>Tax-season Reactivation — ${new Date().toISOString().split("T")[0]}</h2>
          <p><strong>${result.reactivated}</strong> reactivated | <strong>${result.skipped}</strong> still on_hold | <strong>${result.errors}</strong> errors | <strong>${result.scanned}</strong> scanned</p>
          ${reactivatedRows ? `<h3>Reactivated</h3>
          <table style="border-collapse:collapse;width:100%">
            <tr style="background:#f5f5f5"><th style="padding:6px 12px;border:1px solid #ddd;text-align:left">Company</th><th style="padding:6px 12px;border:1px solid #ddd;text-align:left">Action</th></tr>
            ${reactivatedRows}
          </table>` : ""}
          ${errorRows ? `<h3 style="margin-top:16px;color:#c00">Errors</h3>
          <table style="border-collapse:collapse;width:100%">
            <tr style="background:#f5f5f5"><th style="padding:6px 12px;border:1px solid #ddd;text-align:left">Company</th><th style="padding:6px 12px;border:1px solid #ddd;text-align:left">Error</th></tr>
            ${errorRows}
          </table>` : ""}
          <p style="margin-top:16px;color:#888;font-size:12px">Auto-generated by /api/cron/tax-reactivation</p>
        `
        const encodedSubject = `=?utf-8?B?${Buffer.from(subject).toString("base64")}?=`
        const raw = Buffer.from(
          `From: Tony Durante CRM <support@tonydurante.us>\r\n` +
          `To: support@tonydurante.us\r\n` +
          `Subject: ${encodedSubject}\r\n` +
          `MIME-Version: 1.0\r\n` +
          `Content-Type: text/html; charset=utf-8\r\n\r\n` +
          html
        ).toString("base64url")
        await gmailPost("/messages/send", { raw })
      } catch (emailErr) {
        console.error("Tax reactivation email report failed:", emailErr)
      }
    }

    return NextResponse.json({
      ok: true,
      scanned: result.scanned,
      reactivated: result.reactivated,
      skipped: result.skipped,
      errors: result.errors,
      details: result.details,
    })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    logCron({
      endpoint: "/api/cron/tax-reactivation",
      status: "error",
      duration_ms: Date.now() - startTime,
      error_message: msg,
    })
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
