/**
 * Member Info Form MCP Tools
 *
 * Tools:
 *   member_info_form_create — Create (or retrieve existing) member info request for an MMLLC account.
 *                             Pre-populates from existing members table. Returns form URL only.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"
import { supabaseAdmin } from "@/lib/supabase-admin"
import { APP_BASE_URL } from "@/lib/config"

export function registerMemberInfoTools(server: McpServer) {

  // ───────────────────────────────────────────────────────────
  // member_info_form_create
  // ───────────────────────────────────────────────────────────
  server.tool(
    "member_info_form_create",
    `Create a member info request form for a legacy MMLLC account. Used when existing members need to submit their information (names, ownership %, addresses, representative details for company members).

Idempotent: if a pending request already exists for the account, returns it instead of creating a duplicate.

Pre-populates the form with any existing member data already in the members table.

Returns:
- form_url: direct link to the form (send to primary member)
- admin_preview_url: ?preview=td version for internal testing

No email draft is returned — compose the email manually based on the specific context and relationship with the client.`,
    {
      account_id: z.string().uuid().describe("CRM account UUID (must be an MMLLC account)"),
    },
    async ({ account_id }) => {
      // 1. Validate account
      const { data: account, error: accErr } = await supabaseAdmin
        .from("accounts")
        .select("id, company_name, entity_type")
        .eq("id", account_id)
        .single()

      if (accErr || !account) {
        return { content: [{ type: "text", text: `❌ Account not found: ${account_id}` }] }
      }

      // 2. Check for existing pending request (idempotent)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: existing } = await (supabaseAdmin as any)
        .from("member_info_requests")
        .select("id, token, access_code, status")
        .eq("account_id", account_id)
        .eq("status", "pending")
        .maybeSingle() as { data: { id: string; token: string; access_code: string; status: string } | null }

      let token: string
      let accessCode: string

      if (existing) {
        token = existing.token
        accessCode = existing.access_code
      } else {
        // 3. Get existing members for pre-population
        const { data: members } = await supabaseAdmin
          .from("members")
          .select(
            "member_type, full_name, company_name, ein, email, phone, ownership_pct, is_primary, " +
            "address_street, address_city, address_state, address_zip, address_country, " +
            "representative_name, representative_email, representative_phone, " +
            "representative_address_street, representative_address_city, " +
            "representative_address_state, representative_address_zip, representative_address_country",
          )
          .eq("account_id", account_id)
          .order("is_primary", { ascending: false })

        const prePopulatedData = members?.length
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          ? { members: (members as any[]).map(m => ({ ...m, ownership_pct: m.ownership_pct ? String(m.ownership_pct) : "" })) }
          : null

        // 4. Get primary member's contact_id for the request
        const { data: primaryMember } = await supabaseAdmin
          .from("members")
          .select("contact_id")
          .eq("account_id", account_id)
          .eq("is_primary", true)
          .maybeSingle()

        // 5. Create the request (token + access_code generated by DB defaults)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const { data: created, error: createErr } = await (supabaseAdmin as any)
          .from("member_info_requests")
          .insert({
            account_id,
            contact_id: primaryMember?.contact_id || null,
            status: "pending",
            company_name: account.company_name,
            entity_type: account.entity_type || "Multi Member LLC",
            pre_populated_data: prePopulatedData,
          })
          .select("id, token, access_code")
          .single() as { data: { id: string; token: string; access_code: string } | null; error: unknown }

        if (createErr || !created) {
          const errMsg = createErr instanceof Error ? createErr.message : String(createErr)
          return { content: [{ type: "text", text: `❌ Failed to create member info request: ${errMsg}` }] }
        }

        token = created.token
        accessCode = created.access_code
      }

      const formUrl = `${APP_BASE_URL}/member-info/${token}/${accessCode}`
      const adminPreviewUrl = `${formUrl}?preview=td`

      const lines = [
        `✅ Member info form ${existing ? "(existing)" : "created"} for **${account.company_name}**`,
        ``,
        `**Form URL:** ${formUrl}`,
        `**Admin Preview:** ${adminPreviewUrl}`,
      ]

      return { content: [{ type: "text", text: lines.join("\n") }] }
    },
  )
}
