/**
 * Member Info Form MCP Tools
 *
 * Tools:
 *   member_info_form_create — Create (or retrieve existing) member info request for an MMLLC account.
 *                             Pre-populates from existing members table. Returns form URL only.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"
import { supabaseAdmin } from "@/lib/supabase-admin"
import { APP_BASE_URL } from "@/lib/config"

export function registerMemberInfoTools(server: McpServer) {

  // ───────────────────────────────────────────────────────────
  // member_info_form_create
  // ───────────────────────────────────────────────────────────
  server.tool(
    "member_info_form_create",
    `Create a member info request form for a legacy MMLLC account. Used when existing members need to submit their information (names, ownership %, addresses, representative details for company members).

Idempotent: if a pending request already exists for the account, returns it instead of creating a duplicate.

Pre-populates the form with any existing member data already in the members table.

Returns:
- form_url: direct link to the form (send to primary member)
- admin_preview_url: ?preview=td version for internal testing
- context: company name, members with missing info, primary recipient — use this to draft the email

IMPORTANT — email drafting: do NOT use any hardcoded or generic template. After receiving the form URL and context, compose an email draft that fits the actual reason this form is being sent (e.g. portal access setup, formation completion, bank account opening, compliance update). The tone, language (EN/IT based on contact.language), and framing must match the specific situation. Always show the draft to Antonio for approval before sending.`,
    {
      account_id: z.string().uuid().describe("CRM account UUID (must be an MMLLC account)"),
    },
    async ({ account_id }) => {
      // 1. Validate account
      const { data: account, error: accErr } = await supabaseAdmin
        .from("accounts")
        .select("id, company_name, entity_type")
        .eq("id", account_id)
        .single()

      if (accErr || !account) {
        return { content: [{ type: "text", text: `❌ Account not found: ${account_id}` }] }
      }

      // 2. Check for existing pending request (idempotent)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: existing } = await (supabaseAdmin as any)
        .from("member_info_requests")
        .select("id, token, access_code, status")
        .eq("account_id", account_id)
        .eq("status", "pending")
        .maybeSingle() as { data: { id: string; token: string; access_code: string; status: string } | null }

      let token: string
      let accessCode: string

      // 3. Always fetch members for context (needed for output regardless of existing/new)
      const { data: allMembers } = await supabaseAdmin
        .from("members")
        .select("member_type, full_name, company_name, email, ownership_pct, is_primary, contact_id")
        .eq("account_id", account_id)
        .order("is_primary", { ascending: false })

      if (existing) {
        token = existing.token
        accessCode = existing.access_code
      } else {
        const prePopulatedData = allMembers?.length
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          ? { members: (allMembers as any[]).map(m => ({ ...m, ownership_pct: m.ownership_pct ? String(m.ownership_pct) : "" })) }
          : null

        const primaryMember = allMembers?.find(m => m.is_primary)

        // 4. Create the request (token + access_code generated by DB defaults)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const { data: created, error: createErr } = await (supabaseAdmin as any)
          .from("member_info_requests")
          .insert({
            account_id,
            contact_id: primaryMember?.contact_id || null,
            status: "pending",
            company_name: account.company_name,
            entity_type: account.entity_type || "Multi Member LLC",
            pre_populated_data: prePopulatedData,
          })
          .select("id, token, access_code")
          .single() as { data: { id: string; token: string; access_code: string } | null; error: unknown }

        if (createErr || !created) {
          const errMsg = createErr instanceof Error ? createErr.message : String(createErr)
          return { content: [{ type: "text", text: `❌ Failed to create member info request: ${errMsg}` }] }
        }

        token = created.token
        accessCode = created.access_code
      }

      const formUrl = `${APP_BASE_URL}/member-info/${token}/${accessCode}`
      const adminPreviewUrl = `${formUrl}?preview=td`

      // Build context summary for email drafting
      const primaryMember = allMembers?.find(m => m.is_primary)
      const membersWithMissingInfo = (allMembers ?? []).filter(
        m => !m.email || (!m.full_name && !m.company_name)
      )

      const lines = [
        `✅ Member info form ${existing ? "(existing)" : "created"} for **${account.company_name}**`,
        ``,
        `**Form URL:** ${formUrl}`,
        `**Admin Preview:** ${adminPreviewUrl}`,
        ``,
        `**Context for email drafting:**`,
        `- Primary member: ${primaryMember?.full_name || primaryMember?.company_name || "unknown"} (${primaryMember?.email || "no email"})`,
        `- Members with incomplete info: ${membersWithMissingInfo.length > 0 ? membersWithMissingInfo.map(m => m.full_name || m.company_name || "unnamed").join(", ") : "none — all have emails"}`,
        `- Total members: ${allMembers?.length ?? 0}`,
        ``,
        `Draft an email appropriate to the actual reason this form is being sent. Match language (EN/IT) to the recipient. Show draft to Antonio before sending.`,
      ]

      return { content: [{ type: "text", text: lines.join("\n") }] }
    },
  )
}
